export interface MockUser {
  id: string;
  nickname: string;
  neighborhood: string;
  district?: string; // 대전 5개 구
  role: "owner" | "caretaker";
  bio: string;
  rating: number;
  reviewCount: number;
  pets?: { name: string; breed: string; size: string; emoji: string }[];
  services?: string[];
  isActive?: boolean;
  distance?: string;
  distanceKm?: number;
  profileEmoji: string;
  pricePerHour?: number;
  canHandleLargeDogs?: boolean;
  hasTrainerCert?: boolean;
  isVerified?: boolean;
  completedWalks?: number;
  responseTime?: string;
  specialBadge?: string; // 특별 뱃지
}

export interface MockRequest {
  id: string;
  type: "walk_partner" | "caretaker" | "walk_request" | "emergency" | "short_care";
  title: string;
  requester: string;
  neighborhood: string;
  date: string;
  time: string;
  duration: string;
  petName: string;
  petEmoji: string;
  status: "pending" | "accepted" | "completed" | "cancelled";
  isUrgent?: boolean;
  description: string;
}

export const NEIGHBORHOODS = [
  "유성구",
  "둔산",
  "관평",
  "노은",
  "봉명",
  "대덕구",
  "중구",
  "동구",
  "서구",
];

export const MOCK_CARETAKERS: MockUser[] = [
  {
    id: "c1",
    nickname: "강아지사랑 민지",
    neighborhood: "궁동",
    district: "유성구",
    role: "caretaker",
    bio: "3년 경력의 반려동물 돌봄 전문가입니다. 소형견 전문이에요",
    rating: 4.9,
    reviewCount: 47,
    services: ["긴급 방문 돌봄", "대신 산책"],
    isActive: true,
    distance: "0.3km",
    distanceKm: 0.3,
    profileEmoji: "👩",
    pricePerHour: 15000,
    canHandleLargeDogs: false,
    hasTrainerCert: false,
    isVerified: true,
    completedWalks: 128,
    responseTime: "5분 이내",
  },
  {
    id: "c2",
    nickname: "산책왕 준혁",
    neighborhood: "둔산동",
    district: "서구",
    specialBadge: "대전 산책 전문가",
    role: "caretaker",
    bio: "매일 아침 산책하는 걸 좋아해요. 대형견도 OK!",
    rating: 4.7,
    reviewCount: 32,
    services: ["대신 산책", "긴급 방문 돌봄"],
    isActive: true,
    distance: "0.8km",
    distanceKm: 0.8,
    profileEmoji: "👨",
    pricePerHour: 18000,
    canHandleLargeDogs: true,
    hasTrainerCert: true,
    isVerified: true,
    completedWalks: 89,
    responseTime: "10분 이내",
  },
  {
    id: "c3",
    nickname: "펫케어 수빈",
    neighborhood: "관평동",
    district: "유성구",
    role: "caretaker",
    bio: "수의대 재학 중입니다. 건강 체크도 해드려요!",
    rating: 5.0,
    reviewCount: 18,
    services: ["긴급 방문 돌봄", "대신 산책"],
    isActive: false,
    distance: "1.2km",
    distanceKm: 1.2,
    profileEmoji: "👩‍🎓",
    pricePerHour: 20000,
    canHandleLargeDogs: true,
    hasTrainerCert: false,
    isVerified: true,
    completedWalks: 45,
    responseTime: "30분 이내",
  },
  {
    id: "c4",
    nickname: "노은동 지현",
    neighborhood: "노은동",
    district: "유성구",
    role: "caretaker",
    bio: "두 마리 강아지를 키우고 있어요. 경험 많습니다!",
    rating: 4.8,
    reviewCount: 25,
    services: ["긴급 방문 돌봄", "대신 산책"],
    isActive: true,
    distance: "1.5km",
    distanceKm: 1.5,
    profileEmoji: "👩",
    pricePerHour: 12000,
    canHandleLargeDogs: true,
    hasTrainerCert: false,
    isVerified: false,
    completedWalks: 67,
    responseTime: "15분 이내",
  },
  {
    id: "c5",
    nickname: "봉명동 태양",
    neighborhood: "봉명동",
    district: "유성구",
    role: "caretaker",
    bio: "퇴직 후 반려동물 돌봄을 시작했어요. 정성껏 돌봐드립니다.",
    rating: 4.6,
    reviewCount: 61,
    services: ["긴급 방문 돌봄", "대신 산책"],
    isActive: true,
    distance: "2.1km",
    distanceKm: 2.1,
    profileEmoji: "👴",
    pricePerHour: 10000,
    canHandleLargeDogs: false,
    hasTrainerCert: false,
    isVerified: true,
    completedWalks: 203,
    responseTime: "5분 이내",
  },
  {
    id: "c6",
    nickname: "훈련사 하나",
    neighborhood: "어은동",
    district: "유성구",
    specialBadge: "공인 훈련사",
    role: "caretaker",
    bio: "반려견 행동교정 전문 훈련사입니다. 산책 중 기본 훈련도 가능해요.",
    rating: 4.9,
    reviewCount: 38,
    services: ["대신 산책", "긴급 방문 돌봄"],
    isActive: true,
    distance: "0.6km",
    distanceKm: 0.6,
    profileEmoji: "👩‍🏫",
    pricePerHour: 25000,
    canHandleLargeDogs: true,
    hasTrainerCert: true,
    isVerified: true,
    completedWalks: 156,
    responseTime: "10분 이내",
  },
  {
    id: "c7",
    nickname: "대흥동 서연",
    neighborhood: "대흥동",
    district: "중구",
    role: "caretaker",
    bio: "중구 토박이! 보문산 산책 전문이에요.",
    rating: 4.7,
    reviewCount: 29,
    services: ["대신 산책", "긴급 방문 돌봄"],
    isActive: true,
    distance: "1.0km",
    distanceKm: 1.0,
    profileEmoji: "👩",
    pricePerHour: 14000,
    canHandleLargeDogs: false,
    hasTrainerCert: false,
    isVerified: true,
    completedWalks: 72,
    responseTime: "10분 이내",
    specialBadge: "대전 산책 전문가",
  },
  {
    id: "c8",
    nickname: "판암동 동현",
    neighborhood: "판암동",
    district: "동구",
    role: "caretaker",
    bio: "대청호 산책 전문! 자연 속 산책을 좋아합니다.",
    rating: 4.5,
    reviewCount: 19,
    services: ["대신 산책"],
    isActive: true,
    distance: "3.2km",
    distanceKm: 3.2,
    profileEmoji: "👨",
    pricePerHour: 13000,
    canHandleLargeDogs: true,
    hasTrainerCert: false,
    isVerified: false,
    completedWalks: 41,
    responseTime: "20분 이내",
  },
  {
    id: "c9",
    nickname: "신탄진 유진",
    neighborhood: "신탄진동",
    district: "대덕구",
    role: "caretaker",
    bio: "계족산 황톳길 산책 전문가! 자연 치유 산책 해드려요.",
    rating: 4.8,
    reviewCount: 34,
    services: ["대신 산책", "긴급 방문 돌봄"],
    isActive: true,
    distance: "5.1km",
    distanceKm: 5.1,
    profileEmoji: "👩",
    pricePerHour: 16000,
    canHandleLargeDogs: true,
    hasTrainerCert: true,
    isVerified: true,
    completedWalks: 95,
    responseTime: "15분 이내",
    specialBadge: "대전 산책 전문가",
  },
  {
    id: "c10",
    nickname: "송촌동 재민",
    neighborhood: "송촌동",
    district: "대덕구",
    role: "caretaker",
    bio: "동춘당공원 근처에 살아요. 소형견 전문입니다.",
    rating: 4.4,
    reviewCount: 15,
    services: ["대신 산책", "긴급 방문 돌봄"],
    isActive: true,
    distance: "4.8km",
    distanceKm: 4.8,
    profileEmoji: "👨",
    pricePerHour: 11000,
    canHandleLargeDogs: false,
    hasTrainerCert: false,
    isVerified: true,
    completedWalks: 38,
    responseTime: "10분 이내",
  },
  {
    id: "c11",
    nickname: "유천동 소희",
    neighborhood: "유천동",
    district: "중구",
    role: "caretaker",
    bio: "남선공원 단골! 소형견 산책 전문이에요.",
    rating: 4.6,
    reviewCount: 22,
    services: ["대신 산책"],
    isActive: true,
    distance: "2.0km",
    distanceKm: 2.0,
    profileEmoji: "👩",
    pricePerHour: 13000,
    canHandleLargeDogs: false,
    hasTrainerCert: false,
    isVerified: true,
    completedWalks: 56,
    responseTime: "15분 이내",
  },
  {
    id: "c12",
    nickname: "도안동 현우",
    neighborhood: "도안동",
    district: "서구",
    role: "caretaker",
    bio: "갑천 생태 호수 공원 전문! 장거리 산책 가능합니다.",
    rating: 4.8,
    reviewCount: 41,
    services: ["대신 산책", "긴급 방문 돌봄"],
    isActive: true,
    distance: "1.8km",
    distanceKm: 1.8,
    profileEmoji: "👨",
    pricePerHour: 17000,
    canHandleLargeDogs: true,
    hasTrainerCert: true,
    isVerified: true,
    completedWalks: 112,
    responseTime: "5분 이내",
    specialBadge: "공인 훈련사",
  },
  {
    id: "c13",
    nickname: "둔산동 은서",
    neighborhood: "둔산동",
    district: "서구",
    role: "caretaker",
    bio: "둔산동 산책 10년차! 아이와 반려견 동시 돌봄 가능해요.",
    rating: 4.9,
    reviewCount: 63,
    services: ["대신 산책", "긴급 방문 돌봄"],
    isActive: true,
    distance: "0.5km",
    distanceKm: 0.5,
    profileEmoji: "👩\u200d\ud83e\uddb0",
    pricePerHour: 16000,
    canHandleLargeDogs: false,
    hasTrainerCert: false,
    isVerified: true,
    completedWalks: 210,
    responseTime: "3분 이내",
    specialBadge: "둔산동 토박이",
  },
  {
    id: "c14",
    nickname: "궁동 정훈",
    neighborhood: "궁동",
    district: "유성구",
    role: "caretaker",
    bio: "KAIST 수의학과 졸업생. 반려동물 건강 체크도 해드려요!",
    rating: 5.0,
    reviewCount: 28,
    services: ["대신 산책", "긴급 방문 돌봄"],
    isActive: true,
    distance: "1.0km",
    distanceKm: 1.0,
    profileEmoji: "🧑\u200d\u2695\ufe0f",
    pricePerHour: 22000,
    canHandleLargeDogs: true,
    hasTrainerCert: true,
    isVerified: true,
    completedWalks: 75,
    responseTime: "5분 이내",
    specialBadge: "수의사 출신 워커",
  },
  {
    id: "c15",
    nickname: "월평동 승재",
    neighborhood: "월평동",
    district: "서구",
    role: "caretaker",
    bio: "월평공원 산책 전문가! 대형견도 자신 있어요.",
    rating: 4.7,
    reviewCount: 39,
    services: ["대신 산책"],
    isActive: true,
    distance: "1.5km",
    distanceKm: 1.5,
    profileEmoji: "👨\u200d\ud83e\uddb1",
    pricePerHour: 14000,
    canHandleLargeDogs: true,
    hasTrainerCert: false,
    isVerified: true,
    completedWalks: 88,
    responseTime: "10분 이내",
  },
];

// 시드 워커 자동 병합 (시연용)
import { SEED_WALKERS } from "./seed-data";
const seedIds = new Set(SEED_WALKERS.map((w) => w.id));
SEED_WALKERS.forEach((sw) => {
  if (!MOCK_CARETAKERS.find((c) => c.id === sw.id)) {
    MOCK_CARETAKERS.push(sw);
  }
});

export const MOCK_OWNERS: MockUser[] = [
  {
    id: "o1",
    nickname: "골든리트리버 맘",
    neighborhood: "유성구",
    role: "owner",
    bio: "골든이랑 매일 아침 산책해요. 같이 걸을 친구 찾아요!",
    rating: 4.8,
    reviewCount: 12,
    pets: [{ name: "골든이", breed: "골든 리트리버", size: "대형", emoji: "🐕" }],
    distance: "0.4km",
    distanceKm: 0.4,
    profileEmoji: "👩",
  },
  {
    id: "o2",
    nickname: "말티즈 아빠",
    neighborhood: "둔산",
    role: "owner",
    bio: "말티즈 두 마리 키워요. 소형견 산책 친구 구해요",
    rating: 4.5,
    reviewCount: 8,
    pets: [
      { name: "뽀삐", breed: "말티즈", size: "소형", emoji: "🐩" },
      { name: "코코", breed: "말티즈", size: "소형", emoji: "🐩" },
    ],
    distance: "0.7km",
    distanceKm: 0.7,
    profileEmoji: "👨",
  },
  {
    id: "o3",
    nickname: "관평동 강아지맘",
    neighborhood: "관평",
    role: "owner",
    bio: "포메라니안 키워요. 출장이 잦아서 돌봄 자주 필요해요.",
    rating: 4.9,
    reviewCount: 20,
    pets: [{ name: "솜이", breed: "포메라니안", size: "소형", emoji: "🦊" }],
    distance: "1.0km",
    distanceKm: 1.0,
    profileEmoji: "👩",
  },
];

export const MOCK_REQUESTS: MockRequest[] = [
  {
    id: "r1",
    type: "emergency",
    title: "긴급! 오늘 오후 방문 돌봄 부탁드려요",
    requester: "골든리트리버 맘",
    neighborhood: "유성구",
    date: "오늘",
    time: "오후 2시",
    duration: "2시간",
    petName: "골든이",
    petEmoji: "🐕",
    status: "pending",
    isUrgent: true,
    description: "갑자기 외출이 생겼어요. 골든 리트리버 대형견인데 순해요!",
  },
  {
    id: "r2",
    type: "walk_request",
    title: "내일 아침 산책 부탁드립니다",
    requester: "말티즈 아빠",
    neighborhood: "둔산",
    date: "내일",
    time: "오전 7시",
    duration: "30분",
    petName: "뽀삐",
    petEmoji: "🐩",
    status: "pending",
    isUrgent: false,
    description: "아침 일찍 출근해야 해서요. 말티즈 소형견이에요.",
  },
  {
    id: "r3",
    type: "short_care",
    title: "주말 단기 돌봄 교환 원해요",
    requester: "관평동 강아지맘",
    neighborhood: "관평",
    date: "이번 주 토요일",
    time: "오전 10시",
    duration: "4시간",
    petName: "솜이",
    petEmoji: "🦊",
    status: "pending",
    isUrgent: false,
    description: "포메라니안이에요. 다음 주에 제가 대신 봐드릴게요!",
  },
  {
    id: "r4",
    type: "walk_request",
    title: "저녁 산책 대신 해주실 분",
    requester: "노은동 반려인",
    neighborhood: "노은",
    date: "오늘",
    time: "오후 6시",
    duration: "1시간",
    petName: "초코",
    petEmoji: "🐶",
    status: "pending",
    isUrgent: false,
    description: "비글이에요. 활발해서 운동량이 많이 필요해요.",
  },
];

export const SERVICE_TYPES = {
  owner: [
    {
      id: "walk_partner",
      title: "산책 메이트",
      description: "함께 산책할 반려인 매칭",
      emoji: "🚶",
      color: "#2E7D32",
    },
    {
      id: "find_caretaker",
      title: "돌보미 찾기",
      description: "전문 돌보미에게 돌봄 요청",
      emoji: "🏠",
      color: "#34C759",
    },
    {
      id: "walk_request",
      title: "산책 부탁",
      description: "돌보미에게 산책 위탁",
      emoji: "🐾",
      color: "#FF9500",
    },
    {
      id: "short_care",
      title: "돌봄 교환",
      description: "다른 반려인과 상호 돌봄",
      emoji: "🤝",
      color: "#AF52DE",
    },
  ],
  caretaker: [
    {
      id: "emergency",
      title: "긴급 방문 돌봄",
      description: "집 방문 1~2시간 돌봄",
      emoji: "🚨",
      color: "#FF3B30",
    },
    {
      id: "walk_service",
      title: "대신 산책",
      description: "반려동물 대신 산책",
      emoji: "🦮",
      color: "#34C759",
    },
  ],
};
